name: hello-world
on: push
jobs:
  my-job-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout-step
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and Run tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: ".target/surefire-reports/"
          type: ".xml"
      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
          
      - name: Get All Test xml
        if: success() || failure() # always run even if the previous step fails
        uses: the-coding-turtle/ga-file-list@v0.4.1        
        with:
          directory: "target/surefire-reports"
          file_extension: "xml"
      - name: Read XML file
        if: success() || failure() # always run even if the previous step fails
        id: read_file
        uses: andstor/file-reader-action@v1.0.0
        with: 
          path: D:\a\BratlienHelloWorld\BratlienHelloWorld\target\surefire-reports\TEST-sample.SuitTest.xml
      - name: File contents
        if: success() || failure() # always run even if the previous step fails
        run: echo "${ steps.read_file.outputs.contents }"
      - name: Parser results
        if: success() || failure() # always run even if the previous step fails
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: "https://pulse-7-container.qtestnet.com/webhook/53b32c57-368c-4b9b-a4e0-af11389c5438"
          data: '{"projectId": "106715" ,"testcycle": "6334424","result":"${{ steps.read_file.outputs.contents}}"}'         
         # data: "${{ steps.xml2json.outputs.output }}"         
      - name: invoke chatops pulse with json
        if: success() || failure() # always run even if the previous step fails
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: "https://pulse-7-container.qtestnet.com/webhook/f8525ead-f79b-4afb-8873-b374c421fb5c"
          # data: "${{ steps.xml2json.outputs.output }}"
          data: "${{ steps.read_file.outputs.contents }}"
